version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: user-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    networks:
      - user-network

  redis:
    image: redis:7-alpine
    container_name: user-redis
    ports:
      - "6379:6379"
    networks:
      - user-network

  app:
    build: .
    container_name: user-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      - SPRING_REDIS_HOST=redis
    networks:
      - user-network

volumes:
  mysql_data:

networks:
  user-network:
    driver: bridge